CREATE TABLE IF EXISTS whopipe_video_views (
  view_id INTEGER PRIMARY KEY GENERATED BU DEFAULT,
  video_name TEXT NOT NULL,
  region TEXT NOT NULL,
  date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TYPE department AS ENUM (
  'Electronics',
  'Cleaning',
  'Grocery',
  'Furniture',
  'Stationery',
  'Clothing',
  'DIY',
  'Sports',
  'Homeware',
  'Games',
  'Transport'
);

CREATE TABLE IF NOT EXISTS amazong_products (
  product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price decial(12.2) NOT NULL,
  image TEXT,
  category department NOT NULL
);